/**
 * Emit .kant-shaped documents to disk.
 *
 * This is a deliberate subset of kantext's .kant syntax - enough to
 * round-trip through kantext's parser once the sidecar is wired. We do
 * not implement the full language; we produce a conservative shape:
 *
 *   - ⛩️ block declares Meaning@X entries for each emitted point
 *   - A sibling context block declares the actual hierarchy with
 *     meaning, purpose, fields, and nested children
 *
 * No lists. No booleans. Boolean-ish state is serialized as a Signal
 * (numeric value in a marker neighborhood).
 */

import * as fs from "node:fs";
import * as path from "node:path";
import type { KantFragment, KantPoint, KantScalar, KantSignal } from "./types.js";

const INDENT = "  ";

function isSignal(v: KantScalar | KantSignal): v is KantSignal {
  return typeof v === "object" && v !== null && (v as KantSignal).kind === "signal";
}

function serializeScalar(v: KantScalar | KantSignal): string {
  if (isSignal(v)) {
    const marker = v.marker ? ` # ${v.marker}` : "";
    return `${v.value}${marker}`;
  }
  if (typeof v === "number") return String(v);
  return JSON.stringify(v);
}

function serializePoint(name: string, point: KantPoint, depth: number): string {
  const pad = INDENT.repeat(depth);
  const lines: string[] = [`${pad}${name}:`];
  if (point.meaning !== undefined) lines.push(`${pad}${INDENT}meaning: ${JSON.stringify(point.meaning)}`);
  if (point.purpose !== undefined) lines.push(`${pad}${INDENT}purpose: ${JSON.stringify(point.purpose)}`);
  if (point.fields) {
    for (const [k, v] of Object.entries(point.fields)) {
      lines.push(`${pad}${INDENT}${k}: ${serializeScalar(v)}`);
    }
  }
  if (point.children) {
    for (const [childName, child] of Object.entries(point.children)) {
      lines.push(serializePoint(childName, child, depth + 1));
    }
  }
  return lines.join("\n");
}

function serializeMeaningBlock(point: KantPoint, pathFromBase: string, basePath: string, out: string[]): void {
  const fullPath = pathFromBase ? `${basePath}${pathFromBase}` : basePath;
  const anchor = pathFromBase ? pathFromBase.split("/").filter(Boolean).pop()! : basePath.split("/").filter(Boolean).pop()!;
  if (point.meaning !== undefined || point.purpose !== undefined) {
    out.push(`  Meaning@${anchor}:`);
    out.push(`    Category: ${fullPath}`);
    if (point.meaning !== undefined) out.push(`    meaning: ${JSON.stringify(point.meaning)}`);
    if (point.purpose !== undefined) out.push(`    purpose: ${JSON.stringify(point.purpose)}`);
  }
  if (point.children) {
    for (const [childName, child] of Object.entries(point.children)) {
      serializeMeaningBlock(child, `${pathFromBase}/${childName}`, basePath, out);
    }
  }
}

export function serializeFragment(fragment: KantFragment): string {
  const header = [
    `# Projected fragment`,
    `# producer: ${fragment.producer}`,
    `# producedAt: ${fragment.producedAt}`,
    `# basePath: ${fragment.basePath}`,
    `#`,
    `# Auto-generated by ue-mcp. Do not hand-edit.`,
    `# Overrides belong in repo-local .ue-mcp/*.kant layers.`,
    "",
  ].join("\n");

  const meaningLines: string[] = ["⛩️:"];
  for (const [name, point] of Object.entries(fragment.points)) {
    serializeMeaningBlock(point, `/${name}`, fragment.basePath, meaningLines);
  }

  // Instance tree is always rooted at UE@UE: with fragment.points nested
  // under fragment.basePath. This keeps composition trivial - every
  // projected layer and every hand-authored layer attaches at a real
  // path in the /UE address space, no anchor-to-path lookup required.
  const baseSegments = fragment.basePath.split("/").filter(Boolean);
  if (baseSegments[0] !== "UE") {
    throw new Error(`basePath must be rooted at /UE, got '${fragment.basePath}'`);
  }
  const pathSegments = baseSegments.slice(1);

  const contextLines: string[] = ["UE@UE:"];
  let depth = 1;
  for (const seg of pathSegments) {
    contextLines.push(`${INDENT.repeat(depth)}${seg}:`);
    depth += 1;
  }
  for (const [name, point] of Object.entries(fragment.points)) {
    contextLines.push(serializePoint(name, point, depth));
  }

  return [header, meaningLines.join("\n"), "", contextLines.join("\n"), ""].join("\n");
}

export function writeFragment(fragment: KantFragment, outputDir: string): string {
  const filename = `${fragment.producer}.kant`;
  const fullPath = path.join(outputDir, filename);
  fs.mkdirSync(outputDir, { recursive: true });
  fs.writeFileSync(fullPath, serializeFragment(fragment), "utf-8");
  return fullPath;
}
