import { z } from "zod";
import { categoryTool, bp, type ToolDef } from "../types.js";

export const blueprintTool: ToolDef = categoryTool(
  "blueprint",
  "Blueprint reading, authoring, and compilation. Covers variables, functions, graphs, nodes, components, interfaces, and event dispatchers.",
  {
    read:              bp("Read BP structure incl. SCS components. Params: assetPath", "read_blueprint", (p) => ({ path: p.assetPath })),
    list_variables:    bp("List variables. Params: assetPath", "list_blueprint_variables", (p) => ({ path: p.assetPath })),
    list_functions:    bp("List functions/graphs. Params: assetPath", "list_blueprint_functions", (p) => ({ path: p.assetPath })),
    read_graph:        bp("Read graph nodes. Params: assetPath, graphName", "read_blueprint_graph", (p) => ({ path: p.assetPath, graphName: p.graphName })),
    read_graph_summary: bp("Lightweight graph summary (nodes+edges only, ~10KB). Params: assetPath, graphName?", "read_blueprint_graph_summary", (p) => ({ path: p.assetPath, graphName: p.graphName })),
    get_execution_flow: bp("Trace exec pins from an entry point. Params: assetPath, graphName?, entryPoint?", "get_blueprint_execution_flow", (p) => ({ path: p.assetPath, graphName: p.graphName, entryPoint: p.entryPoint })),
    get_dependencies:   bp("Forward (classes/functions/assets) or reverse (referencers) deps. Params: assetPath, reverse?", "get_blueprint_dependencies", (p) => ({ path: p.assetPath, reverse: p.reverse })),
    create:            bp("Create Blueprint. Params: assetPath, parentClass?", "create_blueprint", (p) => ({ path: p.assetPath, parentClass: p.parentClass })),
    add_variable:      bp("Add variable. Params: assetPath, name, varType", "add_variable", (p) => ({ path: p.assetPath, name: p.name, type: p.varType })),
    set_variable_properties: bp("Edit variable properties. Params: assetPath, name, instanceEditable?, blueprintReadOnly?, category?, tooltip?, replicationType?", "set_variable_properties", (p) => ({ path: p.assetPath, name: p.name, instanceEditable: p.instanceEditable, blueprintReadOnly: p.blueprintReadOnly, category: p.category, tooltip: p.tooltip, replicationType: p.replicationType })),
    create_function:   bp("Create function. Params: assetPath, functionName", "create_function", (p) => ({ path: p.assetPath, functionName: p.functionName })),
    delete_function:   bp("Delete function. Params: assetPath, functionName", "delete_function", (p) => ({ path: p.assetPath, functionName: p.functionName })),
    rename_function:   bp("Rename function. Params: assetPath, oldName, newName", "rename_function", (p) => ({ path: p.assetPath, oldName: p.oldName, newName: p.newName })),
    add_node:          bp("Add graph node. Params: assetPath, graphName?, nodeClass, nodeParams?", "add_node", (p) => ({ path: p.assetPath, graphName: p.graphName ?? "EventGraph", nodeClass: p.nodeClass, nodeParams: p.nodeParams })),
    delete_node:       bp("Delete node. Params: assetPath, graphName, nodeName", "delete_node", (p) => ({ path: p.assetPath, graphName: p.graphName, nodeName: p.nodeName })),
    set_node_property: bp("Set node pin default or struct property. Params: assetPath, graphName, nodeName, propertyName, value", "set_node_property", (p) => ({ path: p.assetPath, graphName: p.graphName, nodeName: p.nodeName, propertyName: p.propertyName, value: p.value })),
    connect_pins:      bp("Wire nodes. Params: sourceNode, sourcePin, targetNode, targetPin, assetPath, graphName?", "connect_pins"),
    add_component:     bp("Add BP component. Params: assetPath, componentClass, componentName?", "add_component", (p) => ({ path: p.assetPath, componentClass: p.componentClass, componentName: p.componentName ?? p.componentClass })),
    remove_component:  bp("Remove SCS component. Params: assetPath, componentName", "remove_component", (p) => ({ path: p.assetPath, componentName: p.componentName })),
    set_component_property: bp("Set property on SCS or inherited component. Params: assetPath, componentName, propertyName, value", "set_blueprint_component_property", (p) => ({ path: p.assetPath, componentName: p.componentName, propertyName: p.propertyName, value: p.value })),
    set_class_default: bp("Set UPROPERTY on Blueprint CDO. Params: assetPath, propertyName, value", "set_class_default", (p) => ({ path: p.assetPath, propertyName: p.propertyName, value: p.value })),
    delete_variable:   bp("Delete a member variable. Params: assetPath, name", "delete_variable", (p) => ({ path: p.assetPath, name: p.name })),
    add_function_parameter: bp("Add input or output parameter to a function. Params: assetPath, functionName, parameterName, parameterType?, isOutput?", "add_function_parameter", (p) => ({ path: p.assetPath, functionName: p.functionName, parameterName: p.parameterName, parameterType: p.parameterType, isOutput: p.isOutput })),
    set_variable_default: bp("Set default value on a BP variable. Params: assetPath, name, value", "set_variable_default", (p) => ({ path: p.assetPath, name: p.name, value: p.value })),
    compile:           bp("Compile Blueprint. Params: assetPath", "compile_blueprint", (p) => ({ path: p.assetPath })),
    list_node_types:   bp("List node types. Params: category?, includeFunctions?", "list_node_types"),
    search_node_types: bp("Search nodes. Params: query", "search_node_types"),
    create_interface:  bp("Create BP Interface. Params: assetPath", "create_blueprint_interface", (p) => ({ path: p.assetPath })),
    add_interface:     bp("Implement interface. Params: blueprintPath, interfacePath", "add_blueprint_interface"),
    list_graphs:       bp("List all graphs in a blueprint. Params: assetPath", "list_blueprint_graphs", (p) => ({ path: p.assetPath })),
    add_event_dispatcher: bp("Add event dispatcher. Params: blueprintPath, name", "add_event_dispatcher"),
    duplicate:         bp("Duplicate blueprint asset. Params: sourcePath, destinationPath", "duplicate_blueprint"),
    add_local_variable: bp("Add function-scope local variable. Params: assetPath, functionName, name, varType?", "add_local_variable"),
    list_local_variables: bp("List local variables in a function. Params: assetPath, functionName", "list_local_variables"),
    validate:          bp("Validate blueprint without saving (compile + collect diagnostics). Params: assetPath", "validate_blueprint"),
  },
  undefined,
  {
    assetPath: z.string().optional().describe("Blueprint asset path"),
    graphName: z.string().optional(), functionName: z.string().optional(),
    name: z.string().optional(), varType: z.string().optional().describe("Variable type"),
    parentClass: z.string().optional(),
    instanceEditable: z.boolean().optional(), blueprintReadOnly: z.boolean().optional(),
    category: z.string().optional(), tooltip: z.string().optional(),
    replicationType: z.string().optional(),
    oldName: z.string().optional(), newName: z.string().optional(),
    nodeClass: z.string().optional(), nodeParams: z.record(z.unknown()).optional(),
    nodeName: z.string().optional(), propertyName: z.string().optional(),
    value: z.unknown().optional(),
    sourceNode: z.string().optional(), sourcePin: z.string().optional(),
    targetNode: z.string().optional(), targetPin: z.string().optional(),
    componentClass: z.string().optional(), componentName: z.string().optional(),
    parameterName: z.string().optional(), parameterType: z.string().optional(),
    isOutput: z.boolean().optional(),
    query: z.string().optional(),
    includeFunctions: z.boolean().optional(),
    blueprintPath: z.string().optional(), interfacePath: z.string().optional(),
    entryPoint: z.string().optional().describe("Event/function name to start exec-flow trace"),
    reverse: z.boolean().optional().describe("get_dependencies: true → referencers of this asset"),
    sourcePath: z.string().optional(), destinationPath: z.string().optional(),
  },
);
