import { z } from "zod";
import type { ToolDef } from "../core/types.js";
import { categoryTool } from "../category-tool.js";
import { actions as epicActions, schema as epicSchema } from "./epic/blueprint.generated.js";
import { specBp, schema as specSchema } from "./specs/blueprint.generated.js";

export const blueprintTool: ToolDef = categoryTool(
  "blueprint",
  "Blueprint reading, authoring, and compilation, including AnimGraph/EventGraph node scripting: add_node, connect_pins, search_node_types, plus variables, functions, graphs, components, interfaces, and event dispatchers.",
  {
    read:              specBp("read", "Read BP structure incl. SCS components AND inherited native components from the CDO (CharacterMesh0, CharMoveComp, etc.). assetPath also accepts a World/umap path such as /Game/Maps/SomeLevel, which resolves to that map's level script Blueprint at PersistentLevel.<MapName>; the result reports blueprintPath and isLevelScript so you can see what answered (#942) (#353/#370).", "read_blueprint"),
    list_variables:    specBp("read", "List variables with name, type (pin category), typeSpec (the add_variable spelling, containers included, e.g. map<name,int>), guid, category, tooltip, exposeOnSpawn, blueprintReadOnly, private, and editFlag ('EditAnywhere'|'EditDefaultsOnly'|'EditInstanceOnly'|'none'). instanceEditable is true only for EditAnywhere and EditInstanceOnly - EditDefaultsOnly is class-defaults-only and reports false (#744). private is reported separately because it is a Blueprint-graph access flag, not a details-panel one. Pass includeValues to add each variable's RESOLVED default from the generated-class CDO (value, valueText, cppType, declaringClass, inherited) plus one packageDirty/persisted verdict for the listing; off by default so the declaration list stays small (#902).", "list_blueprint_variables"),
    list_functions:    specBp("read", "List the whole graph surface of a Blueprint, matching what list_graphs reports. Every entry carries kind ('function' own declaration | 'override' of a parent function | 'interface' implementation | 'event_graph' | 'event' entry point on an event graph | 'macro' | 'delegate_signature' | 'subgraph' collapsed graph | 'inherited'), source ('own'|'parent'|'interface'), graphName, and declaringClass/declaringClassPath where one applies. name and nodeCount are unchanged; nodeCount is 0 for entries that are not graphs (#809).", "list_blueprint_functions"),
    read_graph:        specBp("read", "Read graph nodes. Supports pagination, file dumps, and title/class node filters. assetPath accepts a World/umap path, resolved to that map's level script Blueprint (#942). With includeDefaults, literal FText pin values are returned inline (defaultValue falls back to the pin's text literal, plus an explicit defaultTextValue) and object-ref pins report defaultObject (#743) (#560).", "read_blueprint_graph"),
    read_graph_summary: specBp("read", "Lightweight graph summary (~10KB). Returns nodes plus wires split across two arrays, execEdges and dataEdges, not a single combined edges array. Filterable node list. assetPath accepts a World/umap path, resolved to that map's level script Blueprint (#942) (#560).", "read_blueprint_graph_summary"),
    get_execution_flow: specBp("read", "Trace exec pins from an entry point. assetPath accepts a World/umap path, resolved to that map's level script Blueprint (#942).", "get_blueprint_execution_flow"),
    get_dependencies:   specBp("read", "Forward (classes/functions/assets) or reverse (referencers) deps.", "get_blueprint_dependencies"),
    diff:               specBp("read", "Semantic structural diff between two Blueprints (binary uassets are unreviewable in git). Compares parent class, variables (type/default), functions/macros, components, and per-graph node + connection deltas keyed on stable node GUIDs so edits are matched rather than shown as remove+add. Returns a structured delta plus a human summary and changeCount. Changes read as assetPath (A) to otherPath (B). Revision-based diffing via source control is not implemented, and a revision parameter is refused.", "diff_blueprint"),
    create:            specBp("mutate", "Create Blueprint. assetPath is the full destination, e.g. /Game/Blueprints/BP_Example; a name plus packagePath pair is accepted as the same thing. A .uasset suffix, an object suffix, and backslashes are normalized away rather than reaching the editor as an invalid asset name. Idempotent by path: an existing Blueprint is reported rather than replaced.", "create_blueprint"),
    add_variable:      specBp("mutate", "Add variable. varType accepts bool/int/float/string/name/text/byte/vector/rotator/transform/gameplaytag, object:/Script/Module.Class, struct:/Game/Path/To/Struct, enum:/Game/Path/E_Foo.E_Foo, TSubclassOf<Actor>, or a full class/struct path, and a container over any of those: Type[] or array<Type>, set<Type>, map<KeyType,ValueType> (e.g. map<enum:/Game/Enums/E_Team.E_Team,float>). Unrecognized types are rejected rather than silently defaulting. The result reports resolvedType, the spec the variable really got (#745).", "add_variable"),
    set_variable_properties: specBp("mutate", "Edit variable properties. Note: replication is set with networking(set_property_replicated), and blueprintReadOnly is not writable here - list_variables reports it.", "set_variable_properties"),
    create_function:   specBp("mutate", "Create function.", "create_function"),
    delete_function:   specBp("mutate", "Delete function.", "delete_function"),
    rename_function:   specBp("mutate", "Rename function.", "rename_function"),
    add_node:          specBp("mutate", "Add graph node. For a CallFunction node bound to a custom C++ UFUNCTION, pass nodeParams {functionName, className (or targetClass) = /Script/Module.Class}; the function also resolves against the BP's own component classes and an unambiguous loaded BlueprintCallable function, producing a bound node with pins instead of a stub (#546). nodeClass='CallParent' places a 'Parent: <Function>' call bound to the parent implementation (functionName resolves against ParentClass) so an override graph can chain to the base (#688).", "add_node"),
    delete_node:       specBp("mutate", "Delete a node, addressed by nodeId (the GUID get_connections and find_nodes report) or by nodeName. Prefer the GUID: a title is ambiguous the moment a graph holds two nodes with the same one, and a GUID survives a recompile. A state, conduit or alias in an AnimBP state machine is removed the way animation(remove_state) removes it: every transition touching it goes too, each with its bound graph, and the result lists them in removedTransitions (#1132) (#996).", "delete_node"),
    refresh_node:      specBp("mutate", "Refresh a node, as the editor's Refresh Node does: rebuild its pins from its current definition. A pin whose definition is gone (a removed enum value, a deleted parameter) survives as an orphaned pin while it is still linked and fails the compile; the result lists those in orphanedPins, and breakOrphanedPins=true breaks their links and removes them, listing what it broke in brokenOrphanLinks. Idempotent: reports unchanged when the rebuild moved nothing (#1132).", "refresh_node"),
    disconnect_pins:   specBp("mutate", "Break links on one pin, the inverse of connect_pins. With linkedNodeId (and optionally linkedPinName) only the links to that node or pin are broken; without it every link on the pin is. Every broken link is reported in brokenLinks with nodeId, pinName and direction. Idempotent: a pin with nothing to break reports alreadyDisconnected. Breaking exactly one link carries a connect_pins rollback (#1132).", "disconnect_pins"),
    set_node_property: specBp("mutate", "Set node pin default or struct property.", "set_node_property"),
    connect_pins:      specBp("mutate", "Wire nodes. Address each end by sourceNodeId/targetNodeId (the GUIDs get_connections and find_nodes report) or by sourceNode/targetNode title. Prefer the GUIDs: a title cannot pick one of five identically titled math nodes apart, which is what makes re-targeting wiring by title unsafe. breakExistingSource/breakExistingTarget are applied even when the wire already exists, so they clear every other link on that pin; the result reports alreadyConnected. The rollback is disconnect_pins (#996).", "connect_pins"),
    add_component:     specBp("mutate", "Add BP component. componentClass accepts short names (e.g. 'ChildActorComponent') or full paths. For a ChildActorComponent, pass childActorClass to set its ChildActorClass in the same call (a Blueprint path with or without _C, or a C++ class) (#526).", "add_component"),
    remove_component:  specBp("mutate", "Remove SCS component.", "remove_component"),
    set_component_property: specBp("mutate", "Set property on SCS or inherited component. Inherited components go through the child BP's InheritableComponentHandler override template so the parent stays untouched. Pass value=null to clear a TObjectPtr/SoftObject/WeakObject/UClass/Interface reference (e.g. clear AnimClass on CharacterMesh0) (#420). The Blueprint is saved and the result reports saved; a save that does not reach disk fails the call with saveError, and a read-only or protected package is refused before anything changes (#1109).", "set_blueprint_component_property"),
    set_component_override_materials: specBp("mutate", "Write OverrideMaterials on a mesh-component template (StaticMeshComponent / SkeletalMeshComponent / any UMeshComponent). Pass materialPaths as a string[] of material asset paths (empty array clears). Avoids any TArray<UObject*> coercion on the generic set_component_property path (#442).", "set_component_override_materials"),
    add_timeline_track: specBp("mutate", "Add a track to a Blueprint timeline. Creates the UTimelineTemplate if missing, builds the matching curve asset (float/vector/color/event), applies keyframes, bumps TimelineLength to cover the last key, then recompiles so K2Node_Timeline regenerates its output pins. value is a number for float/event, {x,y,z} for vector, {r,g,b,a} for color (#457)", "add_timeline_track"),
    set_capsule_size: specBp("mutate", "Call UCapsuleComponent::SetCapsuleSize on a CapsuleComponent template (CharacterMovement-friendly path; raw property writes leave the visualizer stale). Pass either or both of halfHeight/radius. Returns the new + previous values (#419).", "set_capsule_size"),
    get_component_property: specBp("read", "Read a single property value from an SCS or inherited component template. Returns the ICH override value for child BPs if one exists.", "get_blueprint_component_property"),
    set_class_default: specBp("mutate", "Set UPROPERTY on Blueprint CDO. Pass value=null to clear an object/class/interface reference (#420).", "set_class_default"),
    delete_variable:   specBp("mutate", "Delete a member variable.", "delete_variable"),
    add_function_parameter: specBp("mutate", "Add input or output parameter to a function. parameterType takes the add_variable vocabulary, containers included (int[], set<Name>, map<Name,int>); an unrecognized type is rejected.", "add_function_parameter"),
    set_variable_default: specBp("mutate", "Set default value on a BP variable.", "set_variable_default"),
    get_variable_default: specBp("read", "Read the RESOLVED default of a BP variable off the generated-class CDO, which is what a write-compile-readback loop has to compare against (list_variables alone only proves the variable exists). Returns value (typed JSON), valueText (UE export text), cppType, declaringClass/declaringClassPath and inherited. It also states whether that value is on DISK: packageDirty is the package's own unsaved-changes flag and persisted is its inverse, so a value written into the CDO but never saved reports persisted=false with a persistenceNote instead of reading back as if it had landed (#931). authoredDefault/matchesAuthoredDefault appear when the variable carries a non-empty authored default string that the next recompile could apply (#902).", "get_blueprint_variable_default"),
    compile:           specBp("mutate", "Compile Blueprint.", "compile_blueprint"),
    list_node_types:   specBp("read", "List node types.", "list_node_types"),
    get_connections: specBp("read", "Read a Blueprint graph's edges, addressed by node GUID. read_graph reports each pin as connected true or false and never says to what, and read_graph_summary carries exec edges but no data edges, so there was no native way to answer \"what feeds this pin\" - which is what verifying or re-targeting wiring needs. Each edge carries fromNodeId/fromPin and toNodeId/toPin plus both node titles and classes, and a data edge also carries its pin category. Nodes are named by GUID because a title is exactly what is ambiguous when a graph holds five \"float * float\" nodes, and a GUID survives a recompile. Every edge is reported once, from its output side, which is the direction it actually has. Omit graphName to read every graph the Blueprint owns. Pass nodeId (GUID or name) to report only the edges into and out of that node (#996).", "get_blueprint_connections"),
    find_nodes: specBp("read", "Find nodes anywhere in ONE Blueprint, across every graph it owns including collapsed and nested ones. Narrow by `titles` (case-insensitive substrings matched against the node title), `nodeClasses` (exact class names such as K2Node_VariableGet), or `variableName` with an optional `variableAccess` of get|set|any - which is how you find every read and write of a member, the variable analogue of search_call_sites. The three are alternatives rather than a conjunction, so one pass answers \"every get of bIsAiming, plus anything titled Sprint\". read_graph takes one named graph at a time and does not descend into a collapsed subgraph; this walks them all. Each hit carries the graph selector list_graphs reports, the node title, class and GUID, which filter matched it, and for a variable node the member name, whether it is a get or a set, and its parent class. authoredOnly (default true) leaves out transient compiler graphs. A call naming none of the three filters is refused rather than dumping the Blueprint (#998/#1015).", "search_blueprint_nodes"),
    search_call_sites: specBp("read", "Find authored call-site NODES for named functions across a whole directory in ONE call, including nested and collapsed graphs. Replaces the enumerate-every-Blueprint / read-every-graph sweep that overwhelms the bridge on a large project. Narrowing is done by the Asset Registry BEFORE any package is loaded: candidates come from a recursive Blueprint filter over `directory`, then every candidate whose package does not depend on a package declaring one of `functionNames` is ruled out unloaded. That step is reported (stats.narrowedByRegistry, stats.blueprintsSkippedByRegistry) and can be turned off with narrowByRegistry=false; it is also skipped automatically when a requested name has no resolvable declaring class, so a filter never silently drops a hit. Each hit carries assetPath, packageName, graphName + graphSelector (the same selector list_graphs reports, so it is unambiguous for duplicate nested graph names) + graphObjectPath, nodeId, nodeTitle, memberName, resolvedFunction (absent with unresolvedTarget=true when the function is gone, which is itself an audit finding), declaringClass/declaringClassPath, parentCall, and pinDefaults for unlinked input pins. Pass includeNeighbours for the immediate execution and data neighbours of each call. Level script Blueprints are NOT registry assets (they live inside their map package), so they are excluded unless you pass includeLevelScripts, which sweeps the World assets under the directory and costs a full map load each. Bounded and paginated: limit (default 200, max 1000) + offset, maxBlueprints (default 2000) caps package loads, and dumpToFile writes the whole result set to a JSON file the way read_graph does (#945).", "search_blueprint_call_sites"),
    export_batch: specBp("mutate", "Export many Blueprints to disk in ONE call, for offline analysis. Select with assetPaths[] (a World path resolves to its level script) OR directory (+ recursive?, default true) with an optional parentClass filter (native parents are ruled out by the Asset Registry before loading); includeLevelScripts also sweeps the maps under the directory. Per Blueprint it writes <outputDir>/<package path>.json holding variables (typeSpec, flags), functions (function, override, interface, macro, dispatcher, event and custom_event entries), components (SCS name, class, parent) and every graph with the node, pin and default data read_graph reports plus each pin's linkedTo [{nodeId, pin}]. includeT3D also writes one <package path>/<graph selector>.t3d per graph, the export_nodes_t3d text of the nodes the graph actually holds, so nodes detached from a graph are not exported. outputDir is absolute, or relative to Saved/ (a leading Saved/ names the project's Saved folder), default Saved/UE_MCP/BlueprintExport; a relative path may not leave Saved/. maxAssets (default 200, max 5000) caps the batch and reports truncatedAtMaxAssets. Every asset gets a row with ok and its files, or its error, so one bad asset never fails the batch. Returns files[], the full written file list (#1166).", "export_blueprint_batch"),
    audit_dead_code: specBp("read", "Report-only dead-code audit over a directory (or assetPaths[]). Per Blueprint: unusedFunctions, unusedMacros, unusedCustomEvents and unusedDispatchers (declared here and referenced by no call, macro instance, delegate binding, bound event or widget binding anywhere in the scanned set), unusedVariables (never read or written) and writeOnlyVariables (written, never read), disconnectedFunctionBodies (the entry exec pin is unwired while the function holds executable nodes), unreachableNodes (the head of every exec island with no incoming exec wire that is not an event or entry, with islandSize) and unconnectedPureNodes (pure nodes whose outputs feed nothing). Overrides of parent and interface functions, the construction script and CallInEditor functions and events are excluded. References are counted across the audited Blueprints plus, with scanReferencers (default true), every Blueprint package the Asset Registry says depends on one of them, so a call from outside the directory still counts. Level script Blueprints are audited and scanned only with includeLevelScripts, at a full map load each. Counts are always complete; each finding list is capped at maxSamples (default 20) and the rows at limit (default 200); maxBlueprints (default 2000) caps package loads; dumpToFile writes every row to a JSON file the way read_graph does. Findings are candidates to review: a member reached only from C++ or by a runtime string reads as unused (#1166).", "audit_blueprint_dead_code"),
    search_node_types: specBp("read", "Search placeable nodes across every loaded Blueprint function library (KismetMathLibrary, GameplayStatics, custom libraries) plus UEdGraphNode classes. Matches the C++ name, the palette label from DisplayName metadata, and Keywords metadata, ignoring case/spaces/underscores, so 'is point in box' finds IsPointInBox and 'vector length' finds VSize. Results are ranked and each carries an addNode block (nodeClass + nodeParams incl. targetClass) that add_node accepts verbatim (#808).", "search_node_types"),
    create_interface:  specBp("mutate", "Create BP Interface. Idempotent by path: an existing interface is reported rather than replaced.", "create_blueprint_interface"),
    add_interface:     specBp("mutate", "Implement interface.", "add_blueprint_interface"),
    override_function: specBp("mutate", "Override an inherited interface implementation (inherited via the parent class) or an overridable parent virtual function, with the matching signature so it actually binds as the override (create_function makes a blank, non-binding graph). Returns kind ('function' with a graphName, or 'event' with a nodeId in EventGraph). Event-shaped functions become override events unless preferFunction=true. This is the path for BehaviorTree TASK Blueprint entry points: ReceiveExecuteAI and ReceiveAbortAI on a UBTTask_BlueprintBase child come back as kind='event' in EventGraph, and their FinishExecute / FinishAbort terminators are placed with add_node nodeClass='CallFunction', className='/Script/AIModule.BTTask_BlueprintBase' (#886). Pass interfacePath to also implement the interface first if it is not present. Then wire the body with add_node (use nodeClass='CallParent' to chain to the base implementation). An animation layer override in a child Anim BP is created as an AnimationGraph on the animation schema, mirrored from the graph that declared the layer, so it actually binds instead of compiling to an inert K2 function graph; the result reports graphClass, schemaClass and animationGraph (#894) (#688).", "override_function"),
    list_overridable_functions: specBp("read", "List functions this Blueprint can override: inherited interface implementations and overridable parent virtuals. Each entry has name, source ('interface'|'parent'), declaringClass, canBeEvent (#688).", "list_overridable_functions"),
    list_graphs:       specBp("read", "List all graphs in a blueprint. Returns selector/objectPath plus duplicateIndex/duplicateCount; pass selector back as graphName for unambiguous nested graph edits. assetPath accepts a World/umap path, resolved to that map's level script Blueprint (#942).", "list_blueprint_graphs"),
    resolve_graph:     specBp("read", "Resolve a Blueprint graph name to selectors accepted by read_graph/add_node/connect_pins and other graph actions. assetPath accepts a World/umap path, resolved to that map's level script Blueprint (#942). Duplicate nested AnimBP names such as Locomotion return every match with selectors like Locomotion[3], object paths, and ambiguity metadata.", "resolve_blueprint_graph"),
    add_event_dispatcher: specBp("mutate", "Add event dispatcher (multicast delegate variable + signature graph + UFunction). Without parameters, broadcasters fire void(). With parameters, the signature graph gets typed user pins so K2Node_CallDelegate compiles cleanly (#276). parameters is [{name, type}], where type takes the add_variable vocabulary (bool, float, Vector, enum:/Game/Enums/E_Foo.E_Foo, object:/Script/Engine.Actor, struct:/Script/CoreUObject.Vector, int[], set<Name>, map<Name,int>). Every parameter type is resolved before anything is created, and a missing or unrecognized type refuses the call rather than producing a wildcard pin. The rollback is remove_event_dispatcher.", "add_event_dispatcher"),
    duplicate:         specBp("mutate", "Duplicate blueprint asset.", "duplicate_blueprint"),
    add_local_variable: specBp("mutate", "Add function-scope local variable. varType takes the add_variable vocabulary, containers included (int[], set<Name>, map<Name,int>); an unrecognized type is rejected.", "add_local_variable"),
    list_local_variables: specBp("read", "List local variables in a function.", "list_local_variables"),
    validate:          specBp("read", "Validate blueprint without saving (compile + collect diagnostics).", "validate_blueprint"),
    read_component_properties: specBp("read", "Dump ALL UPROPERTYs on a BP component template incl. array contents (#105).", "read_component_properties"),
    get_component_collision: specBp("read", "Read a component's EFFECTIVE collision: enabled mode, object type, profile name, and the resolved Block/Overlap/Ignore per channel. read_component_properties cannot answer this - it exports BodyInstance as text, and that text carries only CollisionProfileName plus the responses that DIFFER from the profile, so a response INHERITED from the profile (the Pawn profile blocking Camera) is invisible in it. Each channel reports response (what GetCollisionResponseToChannel actually returns), profileResponse, and overridesProfile, so you can see whether an answer came from the profile or from the component. assetPath takes a Blueprint path OR a native class (/Script/MyGame.MyCharacter or 'MyCharacter'), which is how you verify a C++ constructor's SetCollisionResponseToChannel really landed in the CDO after a rebuild. Project trace and object channels appear under their configured names with enumName alongside. channel narrows it to one; includeAllChannels adds the unused GameTraceChannel slots (#925).", "get_component_collision"),
    read_node_property: specBp("read", "Read a node pin default OR a reflected node property for verification (#102).", "read_node_property"),
    reparent_component: specBp("mutate", "Reparent an SCS component under a new parent, recompile and save (#115). Refuses before touching anything when the Blueprint's .uasset is read-only on disk (not checked out) or on a protected mount, and reports saved plus saveError when the write did not reach disk (#932).", "reparent_component"),
    reparent: specBp("mutate", "Change a Blueprint's ParentClass, recompile and save (#138). The save is part of the operation, so writability is checked FIRST: a read-only .uasset (never checked out of source control) or a protected mount returns reason='package_not_writable' naming the file, with nothing reparented, instead of taking the editor down with a fatal save error (#932). A write that still did not reach disk comes back with saved=false and saveError.", "reparent_blueprint"),
    flush_ich: specBp("mutate", "Flush orphaned InheritableComponentHandler override records (invalid component-override entries invisible to read/remove_component). Recompiles + saves. Returns recordsBefore/After/Removed (#580)", "flush_inheritable_component_handler"),
    flush_component_templates: {
      ...specBp("mutate", "Flush orphaned UBlueprint::ComponentTemplates left by deleted Add Component nodes using Unreal's native maintenance routine. Live Add Component templates are preserved. Recompiles + saves only when changed. Returns recordsBefore/After/Removed and removed template identities.", "flush_blueprint_component_templates"),
      timeoutMs: 120_000,
    },
    set_actor_tick_settings: specBp("mutate", "Set actor CDO tick settings (#116).", "set_actor_tick_settings"),
    export_nodes_t3d:  specBp("read", "Export graph nodes as T3D text (Ctrl+C equivalent) for bulk round-trip (#130).", "export_nodes_t3d"),
    import_nodes_t3d:  specBp("mutate", "Paste a T3D node blob into a graph (Ctrl+V equivalent) for bulk authoring (#130).", "import_nodes_t3d"),
    set_cdo_property:  specBp("mutate", "Set UPROPERTY on any C++ class CDO (not just Blueprints) (#182/#183).", "set_cdo_property"),
    get_cdo_properties: specBp("read", "Read UPROPERTY values from any C++ class CDO (#183).", "get_cdo_properties"),
    run_construction_script: specBp("mutate", "Spawn temp actor, run construction script, return generated components and transforms (#195).", "run_construction_script"),
    compile_all: specBp("mutate", "Batch compile + save Blueprints. Returns per-path status (compiled/failed/not_found) (#284)", "compile_blueprints"),
    author: {
      kind: "handler",
      effect: "mutate",
      description: "Author a whole Blueprint in one call: optionally create it (parentClass), then add components, variables and function stubs, then compile - one agent-facing action instead of a dozen add_* round-trips. Params: assetPath, parentClass? (create/ensure the BP if given), components? [{componentClass, componentName?, parentComponent?, childActorClass?}], variables? [{name, varType}], functions? [{functionName}], compile? (default true). Returns per-step results + created flag. (#607)",
      handler: async (ctx, p) => {
        const assetPath = p.assetPath as string;
        if (!assetPath) throw new Error("Missing 'assetPath'");
        const steps: Array<{ step: string; target: string; ok: boolean; result?: unknown; error?: string }> = [];
        const run = async (step: string, target: string, method: string, params: Record<string, unknown>) => {
          try { const result = await ctx.bridge.call(method, params); steps.push({ step, target, ok: true, result }); }
          catch (e) { steps.push({ step, target, ok: false, error: e instanceof Error ? e.message : String(e) }); }
        };
        let created = false;
        if (p.parentClass) {
          try {
            const r = await ctx.bridge.call("create_blueprint", { path: assetPath, parentClass: p.parentClass }) as Record<string, unknown>;
            created = r?.created !== false;
            steps.push({ step: "create", target: assetPath, ok: true, result: r });
          } catch (e) { steps.push({ step: "create", target: assetPath, ok: false, error: e instanceof Error ? e.message : String(e) }); }
        }
        for (const c of (p.components as Array<Record<string, unknown>> ?? [])) {
          await run("add_component", String(c.componentClass ?? ""), "add_component", { path: assetPath, componentClass: c.componentClass, componentName: c.componentName ?? c.componentClass, parentComponent: c.parentComponent, childActorClass: c.childActorClass });
        }
        for (const v of (p.variables as Array<Record<string, unknown>> ?? [])) {
          await run("add_variable", String(v.name ?? ""), "add_variable", { path: assetPath, name: v.name, type: v.varType ?? v.type });
        }
        for (const f of (p.functions as Array<Record<string, unknown>> ?? [])) {
          await run("create_function", String(f.functionName ?? ""), "create_function", { path: assetPath, functionName: f.functionName });
        }
        if ((p.compile ?? true) !== false) {
          await run("compile", assetPath, "compile_blueprint", { path: assetPath });
        }
        const failed = steps.filter(s => !s.ok);
        return { assetPath, created, stepCount: steps.length, failedCount: failed.length, ok: failed.length === 0, steps };
      },
    },
    cleanup_graph: specBp("mutate", "Remove orphan/corrupted nodes (no class, blank title+no pins, missing target UFunction) (#285).", "cleanup_graph"),
    connect_pins_batch: specBp("mutate", "Apply many pin connections in one call (single compile + save) (#267).", "connect_pins_batch"),
    set_node_position: specBp("mutate", "Move a graph node to (posX, posY) (#277).", "set_node_position"),
    auto_layout: specBp("mutate", "Topological layered layout for a graph. Eliminates the (0,0) stack from programmatic add_node. This has no inverse: it rewrites every node's position and set_node_position moves one node per call. It answers that by returning previousPositions, every node's coordinates from before the layout ran, which you replay through set_node_position to undo it. That capture is skipped above previousPositionsLimit nodes (default 200) so a large EventGraph does not return an unbounded array; capturePreviousPositions=true forces it on at any size, and the result says through previousPositionsCaptured which of the two happened. Decide BEFORE running it: once the layout has run the old coordinates are gone (#277).", "auto_layout_graph"),

    list_interfaces: specBp("read", "List the interfaces this Blueprint implements AND the ones it inherits from anywhere in its parent chain. The two halves are told apart by source: an inherited entry carries inheritedFrom, naming the ancestor class that declares it, which for a grandparent is not the immediate parent; an entry the Blueprint declares itself has no ancestor to name and carries no inheritedFrom. Where an inherited interface extends another the base is listed as well, since declaring the derived one puts the base in force too. Every function each declares is reported and whether anything actually answers it: implementedAs is 'graph' (a function graph), 'event' (an override event on the event graph, which is what an interface function with no outputs becomes) or 'missing'. add_interface creates the contract; this is the only thing that reports whether the contract is met, and unimplementedCount is the number to watch. removable is false for an inherited interface, which remove_interface refuses.", "list_blueprint_interfaces"),
    remove_interface: specBp("mutate", "Stop implementing an interface. The paired remove for add_interface, which until now had no inverse and therefore emitted no rollback. preserveFunctions=true keeps the implementations as ordinary Blueprint functions and is the non-destructive form; the default false deletes the interface's function graphs with it, and the result says so through rollbackLossy and names what re-adding would restore. Idempotent: an interface that is not implemented reports alreadyRemoved. An INHERITED interface is refused by name, and the refusal names the ancestor that declares it, which for a grandparent is not the immediate parent: reparenting or editing that class is the only way to drop it.", "remove_blueprint_interface"),

    set_function_properties: specBp("mutate", "Set the flags and metadata of a Blueprint function or macro: pure, isConst, accessSpecifier, category, tooltip, keywords, compactNodeTitle, callInEditor, threadSafe, deprecated, deprecationMessage. These are NOT UPROPERTYs on the asset - they live on the function graph's entry node as FUNC_ flags and FKismetUserDeclaredFunctionMetadata - so asset(set_property) cannot reach them. Validates everything before writing anything, reports existed plus unchanged when the request is already the current state, and the rollback restores exactly the fields this call changed. A macro accepts the metadata half only; the flag half is refused by name because a macro compiles to no UFunction.", "set_function_properties"),

    list_graph_parameters: specBp("read", "Read the parameter signature of a function, macro, event-dispatcher signature or custom event: inputs and outputs with name, type, default value, by-ref and const. The read half of add_function_parameter and edit_graph_parameters. The reported type is the same string the write half accepts (int[], set<Name>, map<Name,int>, object:/Script/Engine.Actor), so a read can be echoed straight back as a call; typeRoundTrips is false for the few pin categories that vocabulary cannot spell. Name exactly one target.", "list_graph_parameters"),
    edit_graph_parameters: specBp("mutate", "Full parameter CRUD over one mechanism, for every node that owns user-defined pins: a function, a macro, an event-dispatcher signature or a custom event. op=add appends one (creating the function's return node on the first output), remove deletes it, rename rewrites it after probing for a collision so a clash refuses instead of half-renaming, set_type retypes it, set_default writes its default as export text, reorder takes the COMPLETE order and validates every entry before a single pin moves. This is what closes add_function_parameter's documented missing remove. isOutput selects the return side; a custom event and a dispatcher signature are input-only and say so.", "edit_graph_parameters"),

    rename_variable: specBp("mutate", "Rename a member variable, rewriting every get and set node in this Blueprint's graphs, the RepNotify function name and the SCS entry for a component variable. delete_variable plus add_variable loses all of them. Reports referencesBefore, referencesUpdated and referencesStillOnOldName, so the fixup is counted rather than asserted. Refuses a name already taken by another variable on this Blueprint or by a property on the parent class, naming what is taken. Self-inverse rollback. Other Blueprints bind this member by its variable GUID, which the rename preserves; asset(get_asset_referencers) plus compile_all confirms them.", "rename_blueprint_variable"),
    get_variable_metadata: specBp("read", "Read every metadata key on a member or local variable (ClampMin, UIMin, EditCondition, Bitmask, BitmaskEnum, MakeEditWidget, MultiLine, and so on). list_variables reports the declaration and set_variable_properties covers category, tooltip and the edit flags; this is the arbitrary-key half, which is not a UPROPERTY and has no other reader. Pass functionName for a local variable.", "get_blueprint_variable_metadata"),
    set_variable_metadata: specBp("mutate", "Write metadata keys on a member or local variable. metadata is an object of key/value strings; a JSON null value removes that key. Unreal stores every metadata value as text, so ClampMin is '0' and EditCondition is 'bEnabled'. Validates the whole object and proves the variable exists in the named scope before writing anything, because the engine setter silently does nothing for a name it cannot find. Idempotent, and the rollback restores each key's previous value or removes it again if it did not exist. Pass functionName for a local variable.", "set_blueprint_variable_metadata"),
    edit_local_variable: specBp("mutate", "Complete the local-variable CRUD that add_local_variable and list_local_variables leave half-built. op=rename rewrites the get and set nodes inside the function (a remove-then-add pair would delete them), remove drops the declaration, set_type retypes it, set_default writes its default as export text. remove is idempotent and reports alreadyRemoved. A Blueprint that has never compiled has no function signature to address a local variable through, and that is reported by name rather than failing silently.", "edit_local_variable"),

    list_event_dispatchers: specBp("read", "List this Blueprint's event dispatchers with their parameter signatures. A dispatcher is a multicast-delegate member variable PLUS a separate signature graph, and hasSignatureGraph=false is exactly the state that produces a missing SignatureFunction error at compile time, so it is reported rather than left to be discovered.", "list_event_dispatchers"),
    remove_event_dispatcher: specBp("mutate", "Remove an event dispatcher: BOTH the member variable and its signature graph. delete_variable removes only the variable and leaves an orphan graph the compiler still walks. Captures the parameter signature first so the inverse re-declares the same one. Idempotent; a variable that is not a dispatcher is refused by name with its actual type. Bind, Unbind and Call nodes go with the variable and are not restored, and the result says so.", "remove_event_dispatcher"),

    add_custom_event: specBp("mutate", "Add a custom event with a TYPED signature in one call. add_node(nodeClass='CustomEvent') can set the name and nothing else, and has no natural key, so calling it twice silently produces two events; this is idempotent on the event name. parameters is [{name, type}] and becomes the event's output pins. netMode (none|multicast|server|client) with reliable sets the replication flags, and callInEditor exposes the button in the details panel. Every parameter type is validated before the node is created.", "add_custom_event"),

    create_macro: specBp("mutate", "Create a Blueprint macro graph with its input and output signature. Macros could be listed by list_functions and read by read_graph but never authored: create_function makes a function, and there was no macro path at all. inputs and outputs are [{name, type}] and land on the entry and exit tunnel nodes; every type is validated before the graph exists. Idempotent on the macro name, and a clash with an existing function or dispatcher graph is refused because graph names share one namespace.", "create_macro"),
    delete_graph: specBp("mutate", "Delete any graph in a Blueprint, addressed the way list_graphs names one. This is the call for a collapsed subgraph that outlived its composite node: delete_function only walks FunctionGraphs and delete_macro only walks MacroGraphs, so both answer alreadyDeleted for an orphan that list_graphs plainly still reports, and leftover variable gets inside it go on blocking delete_variable. While the owning node still exists, delete_node is the right call instead - it takes the bound graph with it - and this refuses rather than leaving the node behind, unless you pass force. Deleting an event graph is refused for the same reason. Idempotent, and reports what it removed: kind, whether it was orphaned, and how many nodes went with it (#1010).", "delete_graph"),
    delete_macro: specBp("mutate", "Delete a macro graph. Idempotent (alreadyDeleted). Reports orphanedInstances, the number of macro instance nodes elsewhere in the Blueprint that referenced it and are now broken - blueprint(cleanup_graph) removes those. The rollback records the macro's input and output signature so re-creating restores the contract; the BODY is not restored and the result says so.", "delete_macro"),

    read_enum: specBp("read", "Read a UserDefinedEnum's whole definition: description, the bitflags switch, and every enumerator with its index, authored short name, editable display name, numeric value and tooltip. asset(list_enum_values) reports the first four columns; this adds the tooltips, the bitflags state and the description, which nothing else could read. Works on native UEnums too, reporting isUserDefined=false. Returns objectPath, because EnumDescription is an ordinary UPROPERTY and belongs to asset(set_property) rather than to a setter here.", "read_user_defined_enum"),
    reorder_enum_values: specBp("mutate", "Reorder a UserDefinedEnum's enumerators. Enumerator order is authored data with no property behind it, so nothing else could change it. order is the COMPLETE list by display name, authored name or index; a partial list, an unknown entry or a repeat is refused before anything moves, naming the valid values. Idempotent: an order that already holds reports unchanged. The rollback replays the previous order by authored name, which survives further reordering.", "reorder_enum_values"),
    set_enum_metadata: specBp("mutate", "Set a UserDefinedEnum's bitflags switch and its per-enumerator tooltips. The bitflags state is a class metadata key and a tooltip is package metadata keyed by enumerator index, so neither is reachable by a property write. entries is [{name or index, tooltip}] and every entry is resolved before the first write, so a bad entry at position nine leaves the first eight untouched. Idempotent, with a rollback carrying the previous bitflags state and the previous tooltip text keyed by authored name. The enum's own description is a UPROPERTY: use asset(set_property) with propertyName='EnumDescription'.", "set_enum_metadata"),

    read_struct: specBp("read", "Read a UserDefinedStruct's whole definition: compile status, validity including the recursion check, the struct tooltip, and per field the display name, GUID, type, default value, tooltip, editableOnInstance, saveGame, multiLineText, widget3D and metadata. asset(list_struct_fields) reports name, GUID and a display label; everything else here had no reader. Two fields earn their place on their own. type is a round-trippable spec (int[], set<Name>, map<Name,int>, struct:/Script/CoreUObject.Vector) that can be handed back to a write. propertyName is the generated FProperty name (<name>_<n>_<guid>), which is what a DataTable row and any exported default actually carry, and it is a different thing from the display name; nameMatchesProperty reports whether the two still agree, so after a rename you can see whether the storage key still carries the old spelling. That divergence is the visible cost of a GUID-preserving rename, which is what lets existing pins and rows survive one at all.", "read_user_defined_struct"),
    set_struct_field_default: specBp("mutate", "Set a UserDefinedStruct member's default value. A member is an FStructVariableDescription inside the struct's editor data, not a UPROPERTY on the asset, so asset(set_property) cannot reach it; the engine call also parses the text against the member's real property and recompiles the struct so every dependent default is repaired, which a raw write would skip. defaultValue is Unreal export text ('5', 'true', '(X=1.000000,Y=2.000000,Z=0.000000)'); an empty string clears it. Resolve the field by fieldName (display or internal name) or fieldGuid. Idempotent, with a rollback carrying the previous value.", "set_struct_field_default"),
    reorder_struct_fields: specBp("mutate", "Reorder a UserDefinedStruct's members. Member order decides the details-panel layout and the DataTable column order and is authored data with no property behind it. order is the COMPLETE list by display name, internal name or GUID; a partial list, an unknown entry or a repeat is refused before anything moves. Idempotent. A move the engine refuses mid-sequence is reported with complete=false and the count that landed, never as a plain success, and the rollback restores the original order by GUID.", "reorder_struct_fields"),
    edit_struct_metadata: specBp("mutate", "Set a UserDefinedStruct's tooltip and its per-member tooltip, editableOnInstance, saveGame, multiLineText, widget3D and arbitrary metadata, in one batched call. All of these live in the struct's editor data rather than as UPROPERTYs, and each has an engine setter that recompiles the struct. fields is [{fieldName or fieldGuid, tooltip?, editableOnInstance?, saveGame?, multiLineText?, widget3D?, metadata?}]. Every member is resolved and every type-gated switch is checked (multiLineText needs a text-like member, widget3D a Vector or Transform) BEFORE the first write, so a refusal on entry nine leaves entries one through eight untouched. Idempotent; the rollback restores every value by GUID, and states the one thing it cannot: a metadata key that did not exist before is restored to an empty string rather than removed.", "edit_struct_metadata"),
    ...epicActions,
  },
  {
    ...epicSchema,
    // #1057: every key a spec'd handler declares, generated from its C++
    // registration. A key listed again below is shared with the handler-kind
    // author action, and tests/unit/handler-specs.test.ts holds the two to one
    // type.
    ...specSchema,
    assetPath: z.string().optional().describe("Blueprint asset path. Read/graph actions also accept a World/umap path (e.g. /Game/Maps/SomeLevel), resolved to that map's level script Blueprint (#942)"),
    parentClass: z.string().optional().describe("create / author / reparent: the parent class. export_batch: only Blueprints deriving from this class (#1166)"),
    components: z.array(z.record(z.unknown())).optional().describe("author: [{componentClass, componentName?, parentComponent?, childActorClass?}] (#607)"),
    variables: z.array(z.record(z.unknown())).optional().describe("author: [{name, varType}] (#607)"),
    functions: z.array(z.record(z.unknown())).optional().describe("author: [{functionName}] (#607)"),
    compile: z.boolean().optional().describe("author: compile after authoring (default true) (#607)"),
    // Spec'd keys declared again only to keep the bounds a spec cannot state.
    // The spec's type is the same, which the handler-specs unit test holds.
    maxAssets: z.number().int().positive().optional().describe("export_batch: cap on Blueprints exported, default 200, max 5000 (#1166)"),
    maxSamples: z.number().int().nonnegative().optional().describe("audit_dead_code: samples listed per finding kind per Blueprint, default 20, max 500; counts stay complete (#1166)"),
    maxBlueprints: z.number().int().positive().optional().describe("search_call_sites / audit_dead_code: cap on Blueprints loaded, default 2000 (#945/#1166)"),
    offset: z.number().int().nonnegative().optional().describe("Row offset for read_graph, and the older non-resumable form of search_call_sites paging"),
  },
);
