import type { ToolDef } from "../core/types.js";
import { categoryTool } from "../surface/category-tool.js";
import { specBp, schema as specSchema } from "./specs/foliage.generated.js";

export const foliageTool: ToolDef = categoryTool(
  "foliage",
  "Foliage instances, types, procedural spawners, sampling and settings. Every FoliageType tunable (Density, Radius, ScaleX/Y/Z, AlignToNormal, GroundSlopeAngle, CullDistance, CastShadow) is a plain property: use set_settings, batch_set_settings_where or asset(set_property), not a typed action. Grass on landscape layers is authored elsewhere and deliberately has no action here: material(add_expression, expressionType=\"LandscapeGrassOutput\") adds the slot node, material(list_expressions) reads it back, asset(create_asset_by_class, className=\"LandscapeGrassType\") makes the grass type, and asset(set_property) fills its GrassVarieties.",
  {
    list_types:    specBp("read", "List foliage types in the level, one row per type per InstancedFoliageActor (foliageActorPath says which), sorted by that pair.", "list_foliage_types"),
    get_settings:  specBp("read", "Read foliage type settings.", "get_foliage_type_settings"),
    sample:        specBp("read", "Count instances per foliage type inside a sphere.", "sample_foliage"),
    create_type:   specBp("mutate", "Create foliage type from mesh.", "create_foliage_type"),
    set_settings:  specBp("mutate", "Modify ONE foliage type's settings. For the same edit across every type matching a condition, use batch_set_settings_where instead of calling this in a loop.", "set_foliage_type_settings"),
    batch_set_settings_where: {
      ...specBp("mutate", "Write settings to every FoliageType whose CURRENT property values match a predicate, with the predicate evaluated in the editor. set_settings is one asset per call and cannot express a condition at all, so 'include_in_hlod=false on every type whose cull distance is set' meant reading 201 assets out, computing the 36 matches client-side, and writing them back one at a time. Candidates come from foliageTypePaths[] (explicit), directory (scan FoliageType assets) or fromLevel=true (types placed in the open level). Predicate fields read the asset's own properties by dotted path, so CullDistance.Max works and a bare name is treated the same as props.<name>; operators are the same vocabulary as level(query_components). dryRun DEFAULTS TO TRUE because this writes to many assets at once, and the preview still resolves every setting path so an unwritable property is reported before the commit. Written values are read back rather than echoed, so a value the property coerced is visible. The inverse is asset(bulk_set_properties) carrying the previous value of every property on every type written, which is the only action that takes DIFFERENT values per asset - two matched types can have had different previous values for the same setting. It is marked lossy when a matched FoliageType lives inside a level rather than as an asset (no assetPath addresses it), and omitted entirely above that action's 500-item batch limit, with the reason stated rather than a record that would restore part of the write. Pass one of foliageTypePaths, directory or fromLevel (#988).", "batch_set_foliage_settings_where"),
      timeoutMs: 300_000,
    },
    add_instances: specBp("mutate", "PAINT foliage into the open level. Nothing else on this surface could place a single instance, so create_type produced an asset that never appeared anywhere. Two modes: transforms[] places each entry exactly, center+radius+count scatters uniformly over a disc. Each candidate is traced onto the geometry beneath it (projectToGround, default true) and then run through the FoliageType's OWN placement rules (applyTypeRules, default true) so the random scale between ScaleX/Y/Z, the random yaw and pitch, align-to-normal within AlignMaxAngle, the Z offset and the CollisionWithWorld test all apply - which is what makes a painted instance behave like one painted by hand. A candidate that hits nothing, or that the type's ground-slope or height range rejects, is reported in skippedCandidates with the reason rather than silently dropped. The type is added to the level's palette if it is not there already. Returns the InstancedFoliageActor it wrote to, and rolls back by removing exactly the transforms it placed. Each transforms entry is {location, rotation?, scale?}.", "add_foliage_instances"),
    remove_instances: specBp("mutate", "Remove foliage instances by index, by exact transform, inside a sphere, or all of a type. The rollback captures each removed instance's world transform and replays it as an add, so this is recoverable up to 2000 instances; the base component an instance was painted onto is not restored. dryRun reports what would go without touching anything. Scope to one InstancedFoliageActor with actorPath when a World Partition map holds the same type on several.", "remove_foliage_instances"),
    get_instances: specBp("read", "Read placed foliage instances with their world transforms, paged. sample only ever returned counts, so there was no way to verify a paint or find what to remove. Filter by type and/or by a sphere; index is the position inside the named actor's info for that type, which is exactly what remove_instances takes.", "get_foliage_instances"),
    add_type_to_level: specBp("mutate", "Put a FoliageType asset into the open level's palette, allocating the instanced component that holds its instances. create_type only makes the asset; until this runs the type is invisible to the level and to the foliage editor. Idempotent: a type already in the level reports existed and allocates nothing.", "add_foliage_type_to_level"),
    remove_type_from_level: specBp("mutate", "Take a FoliageType out of the open level's palette. REFUSES while the type still has instances unless force=true, because removing it destroys them and their transforms are not captured - remove them first with remove_instances, whose rollback does capture them. The FoliageType asset itself is untouched; asset(delete) deletes it.", "remove_foliage_type_from_level"),
    read_spawner: specBp("read", "Read a ProceduralFoliageSpawner: its tile settings, the foliage types it will spawn resolved to real asset paths, and every volume in the open level bound to it with its bounds and whether it has produced anything. The volume half is the part nobody can read off the asset and the usual reason a simulation appears to do nothing. Returns objectPath for the scalar tunables, which are plain properties.", "read_procedural_foliage_spawner"),
    set_spawner_types: specBp("mutate", "Set which foliage types a ProceduralFoliageSpawner spawns. This needs an action rather than a property write: FoliageTypes is a private array whose element object pointer is private too, and every write has to be followed by RefreshInstance or the cached type the simulation actually reads stays stale. Validates every path before writing anything, reports unchanged when the list already matched, reads the result back rather than echoing it, and rolls back to the previous list.", "set_procedural_foliage_spawner_types"),
    simulate_procedural: {
      ...specBp("mutate", "Run the procedural foliage simulation and place what it generates. Address one volume with actorLabel or actorPath, or every volume in the open level bound to one spawner with spawnerPath. Validates every target first (spawner set, type list non-empty, volume bounds non-zero) so a half-simulated set of volumes is not possible, then generates desired instances and traces and places each one under the same type rules as add_instances. Reports generated, placed and skipped per volume. Place the volume itself with level(spawn_volume, volumeType=\"ProceduralFoliageVolume\"), which builds the cube brush a bare spawn leaves empty.", "simulate_procedural_foliage"),
      // The C++ side registers 600s for this: a tile simulation over a
      // large volume plus a world trace per generated point outlives the
      // 30s default, and a client that gives up first reports a failure
      // for work the editor went on to finish.
      timeoutMs: 600_000,
    },
    clear_procedural: specBp("mutate", "Remove every instance a procedural foliage component spawned, matched on the component's own procedural GUID so hand-painted instances of the same type are left alone. Pass one of actorLabel, actorPath or spawnerPath. Reports alreadyRemoved when the component had produced nothing. The inverse re-runs the simulation, which reproduces the cleared content only while the spawner's seed, tile settings and type list are unchanged.", "clear_procedural_foliage"),
  },
  {
    // #1057: every foliage action is spec'd, so every key comes from the C++
    // registrations through the generated module.
    ...specSchema,
  },
);
