import type { ToolDef } from "../types.js";
import { categoryTool } from "../category-tool.js";
import { specBp, schema as specSchema } from "./specs/landscape.generated.js";

export const landscapeTool: ToolDef = categoryTool(
  "landscape",
  "Landscape terrain: info, layers, sculpting, weight painting, materials, splines, proxies.",
  {
    get_info:          specBp("read", "Get landscape setup.", "get_landscape_info"),
    list_layers:       specBp("read", "List paint layers.", "list_landscape_layers"),
    sample:            specBp("read", "Read the surface height AND every paint-layer weight at one world XY. Height and weights come from the landscape's own height and weight data (the merged result of every edit layer), the same data landscape(paint_layer) writes, so they are exact and do not depend on built collision. Layers come back with weight (0..1), weight255 (the weightmap byte the editor shows), the LayerInfo path and its physical material, plus dominantLayer and totalWeight - which is what makes reading a paint weight one call instead of rendering the weightmap to a render target and reading that back. Also returns quad, quadExtent and inBounds, so a zero weight OFF the landscape reads as out of bounds rather than as a measured zero, and traceHeight/normal from a confirmation collision trace (absent when collision is unbuilt or the proxy is streamed out). Position accepts x + y, point {x, y}, or worldX + worldY (#939).", "sample_landscape"),
    sculpt:            specBp("mutate", "Raise, lower or flatten terrain with a circular brush. mode=raise|lower|flatten; amount is world centimetres at full strength (raise/lower), and flatten pulls toward the height under the brush centre. falloff (0..1) is the smoothstepped soft edge. Runs in one transaction and leaves the level dirty and unsaved. Writes into an edit layer (editLayer by name, else editLayerIndex, default 0) - required on UE 5.8, where a write without one is regenerated away by the layer system. Idempotent: a brush that rounds to the height already there reports unchanged=true and updated=false rather than claiming it moved ground. The rollback record carries the exact previous heights over the brush rectangle and replays through set_height_region; above rollbackMaxVertices the response says rollbackOmitted with the reason instead of a record that would restore part of the footprint (#742).", "sculpt_landscape"),
    paint_layer:       specBp("mutate", "Paint a weight layer with a circular brush. The layer must already have a LayerInfo on this landscape (see add_layer_info) - an unregistered name errors and lists the layers that ARE registered instead of silently painting nothing. Weights are written as given - the engine no longer renormalises other layers for you, so set them explicitly if they must sum to 1. Writes into an edit layer (editLayer by name, else editLayerIndex, default 0). Idempotent: a brush that changes no weight reports unchanged=true. The rollback record carries the exact previous weights over the brush rectangle and replays through set_layer_weight_region, with the same rollbackOmitted cap as the region writes (#742).", "paint_landscape_layer"),
    list_edit_layers:  specBp("read", "List the landscape's edit layers by name, in stack order, with guid, visible, locked, heightmapAlpha and weightmapAlpha. These names are what sculpt, paint_layer and the region writes take as editLayer (#1156).", "list_landscape_edit_layers"),
    merge_edit_layers: specBp("mutate", "Re-merge every edit layer into the landscape's final height and weight maps (ALandscape::ForceLayersFullUpdate), then run the update immediately unless updateNow=false. Use after edits that leave the merged result stale. Changes no authored value, so there is no rollback (#1156).", "merge_landscape_edit_layers"),
    list_splines:      specBp("read", "Read landscape splines.", "list_landscape_splines"),
    get_component:     specBp("read", "Inspect component.", "get_landscape_component"),
    set_material:      specBp("mutate", "Set landscape material.", "set_landscape_material"),
    add_layer_info:    specBp("mutate", "Register paint layer (creates LayerInfo asset + binds to active landscape). Idempotent: a layer already registered reports existed and emits no record, so a replay cannot delete a layer it did not create. Rolls back through remove_layer on the parent Landscape actor, which un-registers the layer; marked lossy when the LayerInfo ASSET was created here, because remove_layer deliberately leaves it on disk.", "add_landscape_layer_info"),
    create_layer_info: specBp("mutate", "Standalone LayerInfo asset creation - no landscape required (#251).", "create_landscape_layer_info"),
    create:            specBp("mutate", "Spawn a new ALandscape with a flat heightmap. Defaults match the Editor's Landscape Mode 'create new' (8x8 components, 63 quads/subsection, 2 subsections/component = 1016x1016 quads) (#303).", "create_landscape"),
    get_material_usage_summary: specBp("read", "Per-proxy summary: landscape/hole material paths + component/grass/nanite counts (#150).", "get_landscape_material_usage_summary"),
    list_proxies:      specBp("read", "Enumerate loaded World Partition LandscapeStreamingProxy actors with per-proxy objectPath and worldBounds (origin/extent), sorted by object path, plus loadedProxies + parentLandscapes counts. Unloaded proxies are not spawned as actors, so only loaded ones appear - use this to confirm a proxy is streamed in before trusting a layer/height readback (#733).", "list_landscape_proxies"),
    find_proxy_at:     specBp("read", "Resolve which loaded LandscapeStreamingProxy covers a world X/Y. Returns found/loaded + label, or loaded:false when the covering proxy is streamed out (so a 0-weight readback there is ambiguous, not real) (#733).", "find_landscape_proxy_at"),
    // ── V1 region surface ────────────────────────────────────────────────
    // Every one of these addresses the landscape as a RECTANGLE of vertices
    // rather than as a circular brush, because that is the shape a caller can
    // describe, verify and undo. The rectangle is spelled the same way in all
    // of them: region {minX,minY,maxX,maxY} in landscape vertex indices, the
    // same object with space "world" for centimetres, center + radius for the
    // brush form, or nothing at all for the whole landscape.
    get_height_region: {
      ...specBp("read", "Read the raw uint16 heights over a rectangle of landscape vertices, with min/max/mean reported in raw units AND in world Z so the numbers mean something without a second call. Heights come back as a plain array below arrayEncodingLimit and as a little-endian base64 blob above it, and that blob feeds straight back into set_height_region, so a read-modify-write round trip needs no reformatting. Reports hasUnloadedComponentsInRegion, because on a World Partition map an unloaded component reads as absent rather than as flat ground. Reads the merged surface unless editLayer or editLayerIndex names one, in which case it reads that layer's own contribution.", "get_landscape_height_region"),
      timeoutMs: 120_000,
    },
    set_height_region: {
      ...specBp("mutate", "Write heights over a rectangle of landscape vertices. Accepts heightsBase64 (the blob get_height_region hands back), heights as one number per vertex row-major from (minX,minY), or height / rawHeight to fill the whole rectangle with one value; heightSpace picks whether the numbers are raw uint16 (32768 = the actor's own Z) or world centimetres. Idempotent: a write that changes nothing reports unchanged true and updated false rather than claiming an edit. The rollback record carries the exact previous heights, and when the rectangle is above rollbackMaxVertices the response says rollbackOmitted with the reason instead of emitting a record that would restore only part of it. Requires an edit layer, since a write with none is regenerated away by the layer system.", "set_landscape_height_region"),
      timeoutMs: 300_000,
    },
    get_height_at_point:  specBp("read", "Surface height under one world XY, as both the raw uint16 and the world Z, plus the landscape vertex it was read at. Reads the nearest vertex rather than interpolating, so it can differ from a physics trace by up to half a quad of slope, and it says so. Position accepts x + y, point {x, y}, or worldX + worldY.", "get_landscape_height_at_point"),
    get_normal_at_point:  specBp("read", "World-space surface normal under one world XY, computed by central difference over the neighbouring vertices in world centimetres and rotated into world space, so a non-uniform landscape scale is accounted for. Returns the normal, the slope in degrees and the vertex it was read at.", "get_landscape_normal_at_point"),
    get_slope_at_point:   specBp("read", "Slope under one world XY in degrees from horizontal, in radians, and as a grade percentage, plus the downhill direction as a unit vector. The downhill direction is what routes a road or a river; a slope number alone never is.", "get_landscape_slope_at_point"),
    get_slope_map: {
      ...specBp("read", "Per-vertex slope in degrees over a rectangle, plus min/max/mean and a fixed nine-bucket ten-degree histogram. The buckets are fixed on purpose: they are what a caller reasons about (anything under 15 degrees is buildable) and a configurable bin count would make two runs incomparable. The per-vertex array is returned below arrayEncodingLimit and omitted with a reason above it.", "get_landscape_slope_map"),
      timeoutMs: 120_000,
    },
    sculpt_region: {
      ...specBp("mutate", "Apply one shaping operator over a rectangle: raise, lower, flatten, smooth, mountain, valley, ridge, plateau, crater or terrace. One action rather than ten, because the region resolution, falloff, strength blend, previous-height capture and rollback record are identical for every shape and only the per-vertex kernel differs. amount is world centimetres at full strength, shape picks a radial (ellipse) or edge-relative (rect) falloff, and sharpness controls how peaked the dome operators are. flatten and plateau take targetHeight in world Z, or flattenTo as mean / center / min / max; smooth takes iterations; terrace takes steps; ridge takes ridgeAngle in degrees; crater takes rimPosition and rimRatio. Reports verticesClampedToHeightRange when the shape ran past the uint16 range, since that is a flat-topped mountain rather than a failure.", "sculpt_landscape_region"),
      timeoutMs: 300_000,
    },
    apply_erosion: {
      ...specBp("mutate", "Run hydraulic or thermal erosion over a rectangle. Hydraulic rains on every vertex, routes water to lower four-neighbours, carries sediment to capacity and deposits the rest, then re-deposits whatever is still suspended so the pass does not quietly remove material every run; thermal slumps anything steeper than talusAngle toward it. This is a CPU grid model over the region on the game thread, not the Landscape Mode erosion tool, and the response says so. Cost is vertices times iterations and is refused above maxWork rather than blocking the editor for an unbounded time.", "apply_landscape_erosion"),
      timeoutMs: 600_000,
    },
    import_heightmap: {
      ...specBp("mutate", "Write a 16-bit heightmap file into a region of the landscape. format is png16 (16-bit greyscale PNG) or raw16 (headerless little-endian uint16), inferred from the extension when omitted; an 8-bit image is refused with its real format rather than stretched, because a 256-step heightmap terraces visibly. A raw16 file carries no dimensions, so width and height are required for it. When the image and the region disagree the call refuses and prints the region that WOULD fit, unless resample is true, which bilinearly fits it and says detail was averaged away. minHeight and maxHeight remap the image's 0 and 65535 onto a world Z band, which is the control a heightmap authored elsewhere actually needs. A relative filePath resolves under the project's Saved directory.", "import_landscape_heightmap"),
      timeoutMs: 600_000,
    },
    export_heightmap: {
      ...specBp("mutate", "Write a region's heights out as a 16-bit greyscale PNG or a headerless little-endian uint16 file, for inspection or for a round trip through an external terrain tool. Reports the exact byte count, the region and the height range in raw units and world Z, so the file can be re-imported at the right scale. Exports the merged surface unless editLayer or editLayerIndex names one. No inverse is emitted: the bridge has no delete-file method, and overwriting a file whose previous contents were never read is not undoable, so the response says rollbackOmitted with which of the two cases applied.", "export_landscape_heightmap"),
      timeoutMs: 300_000,
    },
    analyze_terrain: {
      ...specBp("read", "Height and slope distribution over a region, plus largestFlatArea: the biggest axis-aligned rectangle whose every vertex is within slopeThresholdDegrees, in quad indices AND world coordinates with its mean Z. That last part is the answer to where a building fits, which a flat-vertex COUNT never is - ten thousand scattered flat vertices and one flat plateau report the same number. The height histogram takes histogramBins; the slope histogram is fixed at nine ten-degree bands so two runs stay comparable.", "analyze_landscape_terrain"),
      timeoutMs: 120_000,
    },
    get_layer_weight_region: {
      ...specBp("read", "Read one paint layer's 0..255 weights over a rectangle, with min/max/mean and the painted vertex count and fraction. An unregistered layerName is refused with the layers that ARE registered, so a typo and a landscape whose material never declared the layer read differently. Weights come back as an array below arrayEncodingLimit and as base64 above it, in the exact form set_layer_weight_region takes back.", "get_landscape_layer_weight_region"),
      timeoutMs: 120_000,
    },
    set_layer_weight_region: {
      ...specBp("mutate", "Write one paint layer's weights over a rectangle. Accepts weightsBase64 (one uint8 per vertex, the form the getter returns), weights as one number per vertex, or weight / strength as a single 0..1 fraction to fill the rectangle. Idempotent, with the same unchanged/updated reporting as set_height_region, and the rollback record carries the exact previous weights up to rollbackMaxVertices. Weights are written as given: the engine no longer renormalises the other layers for you, so set them explicitly if they must sum to 1.", "set_landscape_layer_weight_region"),
      timeoutMs: 300_000,
    },
    layer_exists:  specBp("read", "Is this paint layer registered on the landscape, and does it have a LayerInfo asset to store weights in? Returns exists, hasLayerInfo, its layerInfoPath, and the full layer list. The two flags are separate because a material can declare a layer that has no LayerInfo assigned, which looks present and fails every paint.", "landscape_layer_exists"),
    add_layer:     specBp("mutate", "Register a paint layer on the landscape, creating the ULandscapeLayerInfoObject asset that its weight data needs and binding it. The counterpart to remove_layer, and the same handler add_layer_info calls. Idempotent: a layer already registered is reported with its existing asset path rather than duplicated.", "add_landscape_layer_info"),
    remove_layer:  specBp("mutate", "Unregister a paint layer and drop its weight data across every component of the landscape. Idempotent: removing a layer that is not there reports alreadyAbsent with the layers that are, rather than failing. NOT undoable through the bridge - the weights are destroyed without being read back first, and the response says so with the reason, so export them with get_layer_weight_region first if they matter. The ULandscapeLayerInfoObject asset itself is left on disk, so add_layer brings the layer back empty.", "remove_landscape_layer"),
    get_holes: {
      ...specBp("read", "Read the landscape visibility mask over a rectangle or at a single world XY, as booleans plus the hole vertex count and fraction. A vertex counts as a hole once its visibility weight passes the engine's own two-thirds threshold, so this action and the renderer agree about what a hole is. A hole only renders, and only stops collision, if the landscape material routes a Landscape Visibility Mask node into opacity mask.", "get_landscape_holes"),
      timeoutMs: 120_000,
    },
    set_holes: {
      ...specBp("mutate", "Punch or fill the landscape visibility mask over a rectangle or at a single world XY. Accepts hole as a single boolean for the whole target, holes as one boolean per vertex, or weightsBase64 to restore exact previous visibility weights (which is the form its own rollback record carries). Unlike every other region action this one does NOT default to the whole landscape when no target is given: that would punch the entire terrain into a hole on a call that forgot a parameter, so it refuses instead.", "set_landscape_holes"),
      timeoutMs: 300_000,
    },
    // ── V17 real-world terrain, the core half ────────────────────────────
    plan_real_world: {
      ...specBp("read", "Turn a real-world extent plus a heightmap file into the exact landscape(create) and landscape(import_heightmap) parameters that reproduce it in engine at true scale. Creates nothing: it is arithmetic against engine invariants a caller cannot restate correctly by hand, namely that a landscape's vertex count is componentCount x subsectionSizeQuads x numSubsections + 1 with subsectionSizeQuads restricted to 7/15/31/63/127/255, and that its uint16 heights only mean metres through the actor's Z scale. Size the tile with realWorldSizeMeters {x,y}, or with boundsLatLon {minLat,minLon,maxLat,maxLon} which is projected on a local tangent plane at the box centre latitude (an approximation, not a datum reprojection, and the response says so). minElevationMeters and maxElevationMeters state what the image's value range means; elevationEncoding full spans 0..65535 across that band, data measures the image's own range and needs sourcePath. Returns the chosen resolution, every legal alternative with its error, the resulting metres per quad, the vertical precision in centimetres, and warnings for resampling, anisotropy, quantisation and exaggeration. Fetching DEM tiles over the network is deliberately NOT part of this: provider APIs, keys and licences change independently of the engine, so that half belongs in a plugin.", "plan_real_world_landscape"),
      timeoutMs: 120_000,
    },
    project_geo_coordinates: specBp("read", "Convert between latitude/longitude and a landscape's world space, in both directions, against the same boundsLatLon the landscape was planned for. Each entry in points is either {lat, lon}, answered with the world X/Y and the sampled surface Z so the point lands ON the terrain, or {x, y}, answered with the geographic coordinate that world position corresponds to - which is what turns analyze_terrain's largestFlatArea back into a real place. northAt says which end of the landscape's Y axis is north, defaulting to minY because a DEM raster's first row is its northern edge and that is how import_heightmap lays one down; getting it wrong mirrors every placement about the middle of the map and nothing about the result looks wrong.", "project_geo_coordinates"),
    refresh_physical_material_collision: {
      ...specBp("mutate", "UE 5.8+: safely refresh physical-material collision data in memory on loaded World Partition LandscapeStreamingProxy actors after a LayerInfo PhysMaterial change. Requires complete registered collision coverage and no pending landscape edit-layer work. Preserves and verifies every raw, complex-live, and simple-live height sample, builds material data before one collision recreation, and fails the whole matched batch on any unsafe result. Filters combine: actorLabels[], guids[], and bounds {min,max}; omitting them targets every loaded proxy up to maxActors (default 256, hard max 1024). Unloaded proxies are untouched; pin them first with level(load_actor_descs). Refuses PIE/SIE and non-World-Partition maps. Persistence is deliberately unsupported because Landscape PreSave can mutate edit-layer collision data; this action never saves packages, and save accepts only false. No inverse: this recomputes derived collision and physical-material data from weightmaps it never writes, so nothing restores the previous build and the response says rollbackPossible=false. Returns loaded/matched/refreshed/failed counts and exact affected package paths.", "refresh_landscape_physical_material_collision"),
      timeoutMs: 600_000,
    },
  },
  {
    // #1057: every landscape action is spec'd, so every key comes from the C++
    // registrations through the generated module.
    ...specSchema,
  },
);
