import { z } from "zod";
import { categoryTool, bp, type ToolDef } from "../types.js";
import { Vec3, Rotator, Color } from "../schemas.js";

export const levelTool: ToolDef = categoryTool(
  "level",
  "Level actors, selection, components, level management, volumes, lights, and splines.",
  {
    get_outliner:       bp("List actors. Params: classFilter?, nameFilter?, world? (editor|pie|auto), limit?", "get_world_outliner"),
    place_actor:        bp("Spawn actor. Params: actorClass, label?, location?, rotation?, scale?, staticMesh?, material?", "place_actor"),
    delete_actor:       bp("Remove actor. Params: actorLabel", "delete_actor"),
    get_actor_details:  bp("Inspect actor. Params: actorLabel OR actorPath, includeProperties?, propertyName?, world? (editor|pie)", "get_actor_details"),
    move_actor:         bp("Transform actor. Params: actorLabel, location?, rotation?, scale?", "move_actor"),
    select:             bp("Select actors. Params: actorLabels[]", "select_actors"),
    get_selected:       bp("Get selection", "get_selected_actors"),
    add_component:      bp("Add component to actor. Params: actorLabel, componentClass, componentName?", "add_component_to_actor"),
    set_component_property: bp("Set component prop. Params: actorLabel, componentName, propertyName, value", "set_component_property"),
    get_current:        bp("Get current level name and path", "get_current_level"),
    load:               bp("Load level. Params: levelPath", "load_level"),
    save:               bp("Save current level", "save_current_level"),
    list:               bp("List levels. Params: directory?, recursive?", "list_levels"),
    create:             bp("Create new level. Params: levelPath?, templateLevel?", "create_new_level"),
    spawn_volume:       bp("Place volume. Params: volumeType, location?, extent?, label?", "spawn_volume"),
    list_volumes:       bp("List volumes. Params: volumeType?", "list_volumes"),
    set_volume_properties: bp("Edit volume. Params: actorLabel, properties", "set_volume_properties"),
    spawn_light:        bp("Place light. Params: lightType, location?, rotation?, intensity?, color?, label?", "spawn_light"),
    set_light_properties: bp("Edit light. Params: actorLabel, intensity?, color?, temperature?, castShadows?, attenuationRadius?", "set_light_properties"),
    build_lighting:     bp("Build lights. Params: quality?", "build_lighting"),
    get_spline_info:    bp("Read spline. Params: actorLabel", "get_spline_info"),
    set_spline_points:  bp("Set spline points. Params: actorLabel, points[], closedLoop?", "set_spline_points"),
    set_actor_material: bp("Set material on actor. Params: actorLabel, materialPath, slotIndex?", "set_actor_material"),
    get_world_settings: bp("Read world settings (GameMode, KillZ, gravity, etc.)", "get_world_settings"),
    set_world_settings: bp("Set world settings. Params: defaultGameMode?, killZ?, globalGravityZ?, enableWorldBoundsChecks?", "set_world_settings"),
  },
  undefined,  // actionDocs auto-generated from descriptions
  {
    actorLabel: z.string().optional(), actorLabels: z.array(z.string()).optional(),
    actorClass: z.string().optional(), label: z.string().optional(),
    location: Vec3.optional(),
    rotation: Rotator.optional(),
    scale: Vec3.optional(),
    properties: z.record(z.unknown()).optional(),
    classFilter: z.string().optional(), nameFilter: z.string().optional(),
    componentClass: z.string().optional(), componentName: z.string().optional(),
    propertyName: z.string().optional(), value: z.unknown().optional(),
    levelPath: z.string().optional(), templateLevel: z.string().optional(),
    directory: z.string().optional(), recursive: z.boolean().optional(),
    volumeType: z.string().optional(),
    extent: Vec3.optional(),
    lightType: z.string().optional(), intensity: z.number().optional(),
    color: Color.optional(),
    temperature: z.number().optional(), castShadows: z.boolean().optional(),
    attenuationRadius: z.number().optional(),
    innerConeAngle: z.number().optional(), outerConeAngle: z.number().optional(),
    quality: z.string().optional(),
    points: z.array(Vec3).optional(),
    closedLoop: z.boolean().optional(),
    staticMesh: z.string().optional().describe("Asset path for static mesh (e.g. /Engine/BasicShapes/Cube.Cube)"),
    material: z.string().optional().describe("Asset path for material to apply at slot 0"),
    materialPath: z.string().optional().describe("Material asset path for set_actor_material"),
    slotIndex: z.number().optional().describe("Material slot index (default 0)"),
    actorPath: z.string().optional().describe("Full actor object path; alternative to actorLabel"),
    includeProperties: z.boolean().optional().describe("Include reflected UPROPERTY values in get_actor_details"),
    world: z.string().optional().describe("World scope: editor (default) or pie"),
    defaultGameMode: z.string().optional(),
    killZ: z.number().optional(),
    globalGravityZ: z.number().optional(),
    enableWorldBoundsChecks: z.boolean().optional(),
  },
);
