import { z } from "zod";
import type { ToolDef } from "../types.js";
import { categoryTool } from "../category-tool.js";
import { actions as epicActions, schema as epicSchema } from "./epic/material.generated.js";
import { specBp, schema as specSchema } from "./specs/material.generated.js";

export const materialTool: ToolDef = categoryTool(
  "material",
  "Materials: create, read, parameters, shading, textures, and graph authoring (expression nodes, connections).",
  {
    read:              specBp("read", "Read material structure. Accepts a Material or a MaterialInstance; an instance answers with its lineage, shading setup and resolved parameters instead of a graph (#952).", "read_material"),
    list_parameters:   specBp("read", "List parameters. On a MaterialInstance each entry carries the resolved value, the parent's defaultValue and whether this instance overrides it (#952).", "list_material_parameters"),
    set_parameter:     specBp("mutate", "Set parameter on MaterialInstance. parameterType (scalar|vector|texture) is auto-detected when omitted. A vector/colour value may be passed as value OR color, shaped {r,g,b,a}, [r,g,b,a] or '(R=..,G=..,B=..,A=..)'. Saves the instance and returns readBack + saved so a set/verify round trip needs no second call (#952).", "set_material_parameter"),
    read_instance:     specBp("read", "Read any MaterialInstance (Constant or Dynamic): parentChain up to the base material, the overrides it holds, and the effective scalar/vector/texture parameter values it renders with (value, parent defaultValue, overridden). To read the material actually on a placed component, including a transient MaterialInstanceDynamic created at runtime, pass actorLabel or actorPath instead of assetPath; world defaults to auto (PIE when running, else editor) (#1114).", "read_material_instance"),
    read_mpc:          specBp("read", "Read a MaterialParameterCollection: every scalar and vector parameter with its stored defaultValue and id. Pass world to also read the live collection instance in that world (liveValue, differsFromDefault), which is what materials sample and what Blueprint writes change (#1116).", "read_material_parameter_collection"),
    set_instance_parent: specBp("mutate", "Set a MaterialInstanceConstant parent.", "set_material_instance_parent"),
    batch_set_instances: specBp("mutate", "Batch reparent + reassign parameters across many Material Instances in one call. Returns per-instance results (#594).", "batch_set_material_instances"),
    clear_instance_parameters: specBp("mutate", "Clear all MaterialInstanceConstant parameter overrides.", "clear_material_instance_parameters"),
    list_static_switches: specBp("read", "List static switch parameters on a Material or MaterialInstance.", "list_material_static_switches"),
    set_static_switch: specBp("mutate", "Set a MaterialInstanceConstant static switch parameter. value is a boolean.", "set_material_static_switch"),
    set_expression_value: specBp("mutate", "Set a value on an expression node. Common typed knobs: value (constant/param default), texturePath (TextureSample/TextureSampleParameter2D default texture). Constant2Vector/3Vector/4Vector and VectorParameter all take value (or color) as {r,g,b,a}, {x,y,z,w}, [r,g,b,a] or '(R=..,G=..)'; Constant2Vector reads the first two components (#979). Saves the material and reports saved. A TextureCoordinate node takes uTiling, vTiling and coordinateIndex, which are separate top-level keys rather than anything inside `value`. For any OTHER UPROPERTY on the expression (e.g. SamplerType, SamplerSource, Group), pass propertyName + value to hit the generic reflection setter. Reports previousValue and rolls back to it where the previous value can be expressed in this action's own vocabulary. Pass functionPath instead of materialPath to edit a node inside a MaterialFunction (index from list_function_expressions); the function is then updated so every material using it recompiles (#1138, #663).", "set_expression_value"),
    set_custom_expression: specBp("mutate", "Read/write a MaterialExpressionCustom (HLSL) node: code, named inputs[] (rebuilds input pins; wire them with connect_expressions targetInput=<name>), outputType (float1|float2|float3|float4|materialAttributes), description. Omit code/inputs to read. Add the node first via add_expression expressionType=Custom, or add_function_expression inside a MaterialFunction (then pass functionPath, #1138) (#617).", "set_custom_expression"),
    disconnect_property: specBp("mutate", "Disconnect a material property input.", "disconnect_material_property"),
    create_instance:   specBp("mutate", "Create material instance. Idempotent by path: an existing instance is reported rather than replaced.", "create_material_instance"),
    create:            specBp("mutate", "Create material. Idempotent by path: an existing material is reported rather than replaced.", "create_material"),
    create_function:   specBp("mutate", "Create a MaterialFunction asset (#463).", "create_material_function"),
    add_function_expression: specBp("mutate", "Add an expression node to a MaterialFunction graph. inputName and inputType apply to a FunctionInput, outputName to a FunctionOutput (#463).", "add_expression_in_function"),
    connect_function_expressions: specBp("mutate", "Wire two expressions inside a MaterialFunction; each expression is named or indexed. The result lists sourceOutputs (the source node's output names by index; an empty name is the default output an omitted sourceOutput selects) and connectedOutputName (#463).", "connect_expressions_in_function"),
    list_function_expressions: specBp("read", "List expression nodes inside a MaterialFunction (#463).", "list_expressions_in_function"),
    build_material:    specBp("mutate", "Build a PBR material from a texture set in one call: creates a TextureSample per entry, picks each sampler type FROM THE TEXTURE (a virtual/UDIM texture silently loses its material connection on recompile unless it samples through the Virtual* variant), wires them, recompiles, saves, and reports which connections survived the recompile. name (+ packagePath) creates the material; materialPath builds into an existing one. assignToMesh puts the result on a StaticMesh or SkeletalMesh (#946).", "build_material"),
    create_simple:     specBp("mutate", "Single-call simple material with optional constants and usages[] (e.g. InstancedStaticMeshes, Nanite, NiagaraSprites). Recompiles + saves in one shot (#225).", "create_material_simple"),
    get_usage:         specBp("read", "Read the EMaterialUsage flags on a material. `usages[]` carries every flag this engine build defines with its `enabled` state and the bUsedWith* `propertyName` behind it, and `enabled[]` is just the ones that are on. Pass a material INSTANCE and the flags come from the base material it resolves to, which is the shader map it renders through: `materialPath` names that material and `inherited` is true (#1004).", "get_material_usage"),
    set_usage:         specBp("mutate", "Turn on EMaterialUsage flag(s) for a material, then recompile and save. Flag names come from this engine own EMaterialUsage reflection, so every usage the build defines is accepted (VolumetricCloud, Voxels, MeshDeformer and the rest included) and `unknown` names only what it truly could not resolve. This only ever turns flags ON: it routes each one through UMaterial::SetMaterialUsage, which is an ensure rather than a write, so a replay also repairs a material whose bit is set but whose shaders were never built. `applied` names the flags this call turned on and `alreadySet` those that were on already. To CLEAR a flag, write its reflected property with editor(set_property): every usage this action recognises is backed by a bUsedWith* UPROPERTY on the material, and the response returns the exact {objectPath, propertyName, value} arguments per flag under `clearCalls`. Clearing a flag does not discard the shader permutations that were compiled for it (#225).", "set_material_usage"),
    set_shading_model: specBp("mutate", "Set shading model.", "set_material_shading_model"),
    set_blend_mode:    specBp("mutate", "Set blend mode.", "set_material_blend_mode"),
    set_domain:        specBp("mutate", "Set material domain. Required for post-process / decal / UI authoring (#299/#356).", "set_material_domain"),
    set_base_color:    specBp("mutate", "Set base color.", "set_material_base_color"),
    connect_texture:   specBp("mutate", "Connect texture to property.", "connect_texture_to_material"),
    add_expression:    specBp("mutate", "Add expression node (#318).", "add_material_expression"),
    connect_expressions: specBp("mutate", "Wire two expressions.", "connect_material_expressions"),
    connect_to_property: specBp("mutate", "Wire expression to material output.", "connect_to_material_property"),
    list_expressions:  specBp("read", "List expression nodes, in the material's own stored order, which is what nodeId indexes into. Set includeInputs to include each node's input wiring (default false). Paged with cursor/limit.", "list_material_expressions"),
    read_graph:        specBp("read", "Read the stored material expression graph without creating an editor graph. Returns the same paged expressions as list_expressions, with inputs carrying inputIndex, inputName, connectedExpressionIndex, connectedOutputIndex, connectedExpressionClass and connectedExpressionDescription, plus every root material input under connections (expressionIndex, outputIndex, expressionClass, expressionDescription; null when disconnected). MaterialAttributes is listed only when the material uses material attributes. Pass expressionIndex (a nodeId) to read just that node and the source expressions its inputs link to, unpaged.", "read_material_graph"),
    delete_expression: specBp("mutate", "Remove expression. expressionName matches a description, class, parameter name, FunctionInput/FunctionOutput name, index or engine name. Pass functionPath instead of materialPath to remove it from a MaterialFunction (#1138).", "delete_material_expression"),
    list_expression_types: specBp("read", "List available expression types, in the curated order they are grouped in. Paged with cursor/limit.", "list_expression_types"),
    recompile:         specBp("mutate", "Recompile material. Pass recompileChildren=true to cascade to every MaterialInstanceConstant whose parent chain reaches this material (#421).", "recompile_material"),
    duplicate:         specBp("mutate", "Duplicate material asset.", "duplicate_material"),
    validate:          specBp("read", "Validate material graph - find orphans, broken refs.", "validate_material"),
    get_shader_stats:  specBp("read", "Shader compile stats, sampler+param counts.", "get_material_shader_stats"),
    export_graph:      specBp("read", "Export material graph as JSON.", "export_material_graph"),
    import_graph:      specBp("mutate", "Rebuild graph from JSON.", "import_material_graph"),
    build_graph:       specBp("mutate", "Build graph from spec.", "build_material_graph"),
    render_preview:    specBp("mutate", "Render preview PNG.", "render_material_preview"),
    begin_transaction: specBp("mutate", "Begin undo transaction.", "begin_material_transaction"),
    end_transaction:   specBp("mutate", "End undo transaction.", "end_material_transaction"),
    // V15 Runtime Virtual Textures. Every SETTING on an RVT asset, on its
    // volume component and in a landscape's virtual texture group is a
    // UPROPERTY, so asset(set_property) / editor(set_property) already writes
    // all of them and none of these actions is a setter. Each one calls an
    // engine function a property write cannot reach, named in its description.
    create_rvt: specBp("mutate", "Create a RuntimeVirtualTexture asset. materialType is validated against RuntimeVirtualTexture::IsMaterialTypeSupported, which is the reason it is a parameter rather than a follow-up property write: a project can disable individual material types to cut shader permutations, and set_property would happily store one that then compiles to nothing. Everything else (tileCount, tileSize, tileBorderSize, compression, adaptive/private/packed page table, continuous update, LOD group) is a plain UPROPERTY: write it with asset(set_property) at the returned objectPath. Reads back the DERIVED layout - size, pageTableSize, layer count and per-layer pixel format and colour space - which no property read produces. Idempotent by path; rollback deletes the asset.", "create_runtime_virtual_texture"),
    read_rvt: specBp("read", "Read a RuntimeVirtualTexture and its whole reference graph: the derived layout (size, pageTableSize, per-layer pixel format, sRGB and YCoCg), every volume bound to it with its transform, every primitive and landscape that writes into it, and every material sample node that reads it. problems[] names the failures that otherwise only show up visually - no volume (so no world bounds), no writer (so every page renders empty), a disabled material type, and the classic one: a sample node whose materialType disagrees with the asset, which decodes the wrong channels and still compiles. level(get_runtime_virtual_texture_summary) answers the level-side question; this answers the asset-side one.", "read_runtime_virtual_texture"),
    add_rvt_volume: specBp("mutate", "Spawn the RuntimeVirtualTextureVolume that gives an RVT its world bounds, bind the asset through the engine's SetVirtualTexture (which re-registers the render state, unlike a raw property write), and fit the volume to what actually writes into the texture. An unfitted volume sits at the origin at unit scale and renders a 100cm cube of the world, so the fit is the point. Idempotent BY BINDING rather than by label: two volumes on one RVT is a real misconfiguration (one wins, the other renders nothing) and an existing binding is reported rather than duplicated. When nothing writes into the RVT yet there is nothing to fit to, and the response says so in boundsFitNote rather than reporting a fit that did not happen. Rollback deletes the actor.", "add_rvt_volume"),
    set_rvt_volume_bounds: specBp("mutate", "Refit an RVT volume to the world, which is the Set Bounds button and is not a property write: it DERIVES a transform from what is in the level. boundsMode='writers' covers every primitive whose RuntimeVirtualTextures array names this RVT; boundsMode='alignActor' matches one actor's box and rotation, which is what a landscape wants because the volume's axes have to be the terrain's axes. The volume's own local extent is read back through CalcBounds and solved against the target box rather than assumed to be a unit cube, so the fit survives engine changes. Honest limitation: it does NOT perform the landscape texel snap (that lives in a module the bridge does not link) and says so when bSnapBoundsToLandscape is set. Rollback restores the previous transform exactly.", "set_rvt_volume_bounds"),
    add_rvt_sampler: specBp("mutate", "Add or rebind the RuntimeVirtualTextureSample node that READS an RVT in a material, then call the engine's InitVirtualTextureDependentSettings, which is the one step add_expression + set_expression_value cannot do: it copies the asset's material type and packed/adaptive page-table flags onto the node and rebuilds its output pins. Setting VirtualTexture alone leaves those stale, which compiles cleanly and decodes the wrong channels. Optionally connects each output pin to the material property of the same name and reports the pins that have no counterpart (WorldHeight, Mask, Mask4, Displacement) rather than dropping them silently. Idempotent by expressionName. MipValueMode, TextureAddressMode and bEnableFeedback stay editor(set_property) territory at the returned expressionObjectPath.", "add_rvt_sampler"),
    add_rvt_output: specBp("mutate", "Add the RuntimeVirtualTextureOutput node that makes a material WRITE into an RVT, and mirror the material's existing BaseColor / Normal / Roughness / Specular / Opacity connections into it, which by hand is one connect_expressions call per channel with each source expression and output index looked up by eye. Reads the node's inputs by NAME through the same GetInput/GetInputName pair connect_expressions uses, so a channel added by an engine version is picked up rather than mis-wired. Inputs with no material counterpart are reported with the call that wires them. Idempotent by expressionName. Note this does not choose WHICH RVT: that is the primitive's RuntimeVirtualTextures array (assign_rvt_to_landscape, or editor(set_property) on a mesh component).", "add_rvt_output"),
    assign_rvt_to_landscape: specBp("mutate", "Assign RVTs to a landscape across EVERY proxy that shares its ULandscapeInfo, not just the actor named. A streaming or World Partition landscape is many ALandscapeStreamingProxy actors, and writing RuntimeVirtualTextures on one of them with set_property leaves the rest rendering nothing into the RVT, which is invisible until the pages come back empty. Also calls PostEditChange plus MarkComponentsRenderStateDirty per proxy, without which the change does not take effect, and checks the two things that make an assignment useless anyway: a landscape material with no RuntimeVirtualTextureOutput node, and an RVT whose material type is disabled for the project. assignMode='set' with an empty list clears the assignment. Rollback replays the named landscape's previous list, with previousPerProxy carrying the exact per-proxy state.", "assign_rvt_to_landscape"),
    // #1131 Material Designer (DynamicMaterial plugin) layer stacks, through reflection.
    create_designer: specBp("mutate", "Create a Material Designer material: a DynamicMaterialInstance asset WITH its Material Designer model, through the plugin's own DynamicMaterialInstanceFactory (asset(create_asset_by_class) leaves the model empty). Seeds a Base Color slot when the new model has none, requests a build and saves. Returns path, modelPath, slotCount and a delete_asset rollback. Needs the Material Designer plugin (#1131).", "create_material_designer"),
    read_designer: specBp("read", "Read a Material Designer (DynamicMaterial) model: material settings (domain, blend mode, shading model, flags), materialProperties with their enabled state and designerSlot, and every slot's layer stack. Each layer carries name, bEnabled, MaterialProperty, blendMode, effectStack and its stages (stageType Base or Mask) with sources, inputs, sub-stages, values, texture UVs and text renderers described recursively; every component reports objectPath, componentPath and writableProperties for set_designer_value. Target a Motion Design shape with actorLabel/actorPath (the first material slot holding a DynamicMaterialInstance, or componentName?/slotIndex?/slotName?), or pass assetPath (a DynamicMaterialInstance, a DynamicMaterialModel, or any object inside one). designerSlot and layerIndex narrow the read. Needs the Material Designer plugin (#1131).", "read_material_designer"),
    set_designer_value: specBp("mutate", "Set one property on a Material Designer component (a layer, stage, value, texture UV, text renderer, the editor-only data's settings) by reflection. Uses the component's own setter when it has one (SetValue, SetOffset, SetTiling, SetText, SetEnabled, SetLayerName) so the model updates the way the Material Designer UI does; otherwise writes the property, calls PostEditChangeProperty and Update, and requests a material build. Address the component by objectPath or componentPath (both reported by read_designer), or by designerSlot? + layerIndex/layerName (+ stage? base|mask|index); componentPath and the layer forms also need assetPath or actorLabel/actorPath. Returns previousValue and a rollback (#1131).", "set_material_designer_value"),
    add_designer_layer: specBp("mutate", "Add a default layer to a Material Designer slot through UDMMaterialSlot::AddDefaultLayer, optionally naming it, then request a material build. Returns the new layer as read_designer describes it; its stages are then set with set_designer_value. designerSlot defaults to the slot mapped to materialProperty (#1131).", "add_material_designer_layer"),
    remove_designer_layer: specBp("mutate", "Remove a layer from a Material Designer slot through UDMMaterialSlot::RemoveLayer, after CanRemoveLayer agrees (a slot keeps its base layer). Address it by objectPath, or by layerIndex or layerName in a target's slot. Runs in an editor transaction; the rollback is one editor undo (#1131).", "remove_material_designer_layer"),
    ...epicActions,
  },
  {
    ...epicSchema,
    // #1057: every key a spec'd handler declares, generated from its C++
    // registration. A key listed again below is shared with hand-written
    // actions, and tests/unit/handler-specs.test.ts holds the two to one type.
    ...specSchema,
    // The spec cannot carry bounds; these keep them, with the type the spec declares.
    slotIndex: z.number().int().min(0).optional().describe("read_instance / *_designer*: material slot index on the mesh component (default 0) (#1114/#1131)"),
    layerIndex: z.number().int().min(0).optional().describe("Material Designer layer index within the slot (#1131)"),
    maxDepth: z.number().int().min(1).optional().describe("read_designer: how deep to describe nested stages and values (default 10) (#1131)"),
  },
);
